### ISSUE TITLE
Is this a work in progress, or a completed example?

### ISSUE THREAD

**Issue by zipzit** [regniblod/node-mongo-docker-compose#1]
I'm still learning this stuff.  With simple download and `docker-compose up` this fails.

Things start off okay.
```
Creating network "nodemongodockercompose_default" with the default driver
Building web
Step 1/6 : FROM node:latest
latest: Pulling from library/node
Status: Downloaded newer image for node:latest
 ---> ...
Step 2/6 : RUN mkdir /app
 ---> Running in ...
Removing intermediate container f2f8529bc084
Step 3/6 : WORKDIR /app
 ---> ...
```
But then, 

```
Step 4/6 : COPY package.json /app/
ERROR: Service 'web' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder811369559/package.json: no such file or directory
```
Am I doing something wrong, or perhaps this is a partially completed project?

Many thanks for sharing what you have already done.

**Comment by regniblod** [comment]
Hey!

Thanks for using my project and actually take the time to open an issue! :)

It fails because there's no `package.json` in the directory. It's ok to fail if you just cloned the project and run `docker-compose up`.

You have to copy `Dockerfile` and `docker-compose.yml` files into your own project, with your own `package.json`, to make it work.

Hope it helps!
